#!/usr/bin/env python


import sys
import os

origdir = os.path.abspath(sys.argv[0] + '/../../home')
dstdir = os.path.expanduser('~')

import subprocess
def shell(args, split='\n'):
    p = subprocess.Popen(args, stdout=subprocess.PIPE, stderr=subprocess.PIPE)
    (stdout, stderr) = p.communicate()
    if p.returncode:
        raise OSError(p.returncode, stderr)
    return filter(None, stdout.decode('utf-8').split(split))

def find(searchdir, args):
    cmdargs = ['find', searchdir]
    cmdargs.extend(args.split())
    cmdargs.append('-print0')
    return shell(cmdargs, split='\0')

dirlinks = set(path.replace('/.link', '') for path in find(origdir, '-type f -name .link'))
def dirlinked(path):
    for dirlink in dirlinks:
        if path == dirlink or path.startswith(dirlink + '/'):
            return True
    return False

dirnew = set(dir for dir in find(origdir, '-type d') if not dirlinked(dir))
filelinks = set(file for file in find(origdir, '-type f -print0 -or -type l') if not dirlinked(file))
links = dirlinks | filelinks

def dstpath(path):
    return path.replace(origdir, dstdir)

def rm_files(paths):
    if paths:
        for path in paths:
            print(path)

        try:
            raw_input('About to delete the above: ')
        except NameError:
            input('About to delete the above: ')

        for path in paths:
            if os.path.islink(path):
                os.unlink(path)
            elif os.path.isfile(path):
                os.remove(path)
            elif os.path.isdir(path):
                os.rmdir(path)
            else:
                raise OSError(path)

if len(sys.argv) > 1 and sys.argv[1] == 'clean':
    rm_files([dstpath(origpath) for origpath in links if os.path.lexists(dstpath(origpath))])
else:
    torm = []
    for origpath in dirnew:
        if os.path.exists(dstpath(origpath)) and not os.path.isdir(dstpath(origpath)):
            torm.append(dstpath(origpath))
    for origpath in links:
        if os.path.exists(dstpath(origpath)) and not os.path.islink(dstpath(origpath)):
            torm.append(dstpath(origpath))

    rm_files(torm)

    for origpath in dirnew:
        if not os.path.exists(dstpath(origpath)):
            os.mkdir(dstpath(origpath))

    for origpath in links:
        if not os.path.exists(dstpath(origpath)):
            os.symlink(origpath, dstpath(origpath))
